mysite/core/urls.py
# encoding: utf-8
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),  # translations

    url('^bot/$', views.CommandReceiveView.as_view(), name='command_receive'),

    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password_reset/complete/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^accounts/profile/$', views.ProfileView.as_view(), name='profile'),

    url(r'^$', views.IndexView.as_view(), name='index'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

from django.conf import settings


urlpatterns = [
    url(r'^', include('core.urls', namespace='core')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('social_django.urls', namespace='social')),
]

# urlpatterns += i18n_patterns(
#     url(r'^', include('core.urls', namespace='core')),
# )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mysite/projects/urls.py
# encoding: utf-8
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.ProjectListView.as_view(), name='list_project'),
    url(r'^(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='detail_project'),

    url(r'^user-project/$', views.UserProjectListView.as_view(), name='list_user_project'),
    url(r'^user-project/create/$', views.UserProjectCreateView.as_view(), name='create_user_project'),
]

mysite/projects/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from taggit.managers import TaggableManager

from courses.models import Course


class Project(models.Model):
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)
    course = models.ForeignKey(Course, related_name='projects', null=True, verbose_name=_('Course'))
    name = models.CharField(_('Name'), max_length=250, unique=True)
    description = models.TextField(_('Description'))
    help_links = models.ManyToManyField('HelpLink', blank=True, verbose_name=_('Help links'))
    max_mark = models.PositiveIntegerField(_('Max mark'), default=10)
    main_project = models.ForeignKey('self', related_name='optional_projects', on_delete=models.CASCADE, blank=True,
                                     null=True, verbose_name=_('Main project'))
    tags = TaggableManager()

    def get_tags(self):
        return self.tags.names()

    def get_tags_str(self):
        return ', '.join(self.tags.names())

    def get_students(self):
        return UserProject.objects.filter(project=self.id).values_list('student__username', flat=True)

    def get_teachers(self):
        return UserProject.objects.filter(project=self.id).values_list('teacher__username', flat=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Project')
        verbose_name_plural = _('Projects')


class UserProject(models.Model):
    student = models.ForeignKey(User, related_name=_('student_projects'), limit_choices_to={'groups__name': 'students'})
    teacher = models.ForeignKey(User, related_name=_('teacher_projects'), limit_choices_to={'groups__name': 'teachers'})
    project = models.ForeignKey(Project, related_name=_('user_projects'))
    started_at = models.DateTimeField(_('Started at'), auto_now_add=True)
    finished_at = models.DateTimeField(_('Finished at'), null=True, blank=True)
    mark = models.PositiveIntegerField(_('Mark'), default=0)

    def __str__(self):
        return ' '.join([self.student.username, self.project.name])

    class Meta:
        verbose_name = _("User's project")
        verbose_name_plural = _("User's projects")


class HelpLink(models.Model):
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)
    name = models.CharField(_('Name'), max_length=250, unique=True)
    description = models.TextField(_('Description'), blank=True, null=True)
    help_link = models.URLField(_('Help link'))

    def __str__(self):
        return self.help_link

    class Meta:
        verbose_name = _('Help link')
        verbose_name_plural = _('Help links')

mysite/projects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from .models import Project, UserProject


class ProjectListView(LoginRequiredMixin, generic.ListView):
    model = Project


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    model = Project
    template_name = 'projects/project_detail.html'

#
# class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
#     model = Project
#     template_name = 'projects/userproject_create.html'
#     success_url = reverse_lazy('projects:list_user_project')
#     fields = ['student', 'teacher', 'project', 'mark']


class UserProjectListView(LoginRequiredMixin, generic.ListView):
    model = UserProject


class UserProjectCreateView(LoginRequiredMixin, generic.CreateView):
    model = UserProject
    template_name = 'projects/userproject_create.html'
    success_url = reverse_lazy('projects:list_user_project')
    fields = ['student', 'teacher', 'project', 'mark']

mysite/projects/templates/projects/project_detail.html
{% extends 'core/index.html' %}

{% load i18n %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="jumbotron">
    <h5>
        <span class="badge badge-default">
            {% if project.main_project %}
            {% trans 'optional' %}
            {% else %}
            {% trans 'main' %}
            {% endif %}
        </span>
        {% for tag in project.get_tags  %}
        {% if forloop.counter|divisibleby:5 %}
        <span class="badge badge-danger">
        {% elif forloop.counter|divisibleby:4 %}
        <span class="badge badge-warning">
        {% elif forloop.counter|divisibleby:3 %}
        <span class="badge badge-info">
        {% elif forloop.counter|divisibleby:2 %}
        <span class="badge badge-success">
        {% else %}
        <span class="badge badge-primary">
        {% endif %}
            {{ tag }}
        </span>
        {% endfor %}
    </h5>
    <h2>{{ project.name }}</h2>
    {% if project.help_links %}
    <p>
        {% for hlink in project.help_links.all %}
        <a href="{{ hlink.help_link }}">{{ hlink.name }}</a> {% if not forloop.last %},{% endif %}
        {% endfor %}
    </p>
    {% endif %}
    <p>{% trans 'Max mark' %}: {{ project.max_mark }}</p>
    {% autoescape off %}{{ project.description }}{% endautoescape %}
    <p>&nbsp;</p>
    <p>
        <small class="text-muted">
            {% blocktrans with updated_at=project.updated_at|timesince %}
            Last updated {{ updated_at }} ago
            {% endblocktrans %}
        </small>
    </p>
</div>
{% if project.optional_projects %}
<div class="card-deck">
    {% for opt_project in project.optional_projects.all %}
    <div class="card">
        <div class="card-header">
            {% blocktrans with points=opt_project.max_mark %}
            Up to {{ points }} points
            {% endblocktrans %}
        </div>
        <div class="card-block">
            <p class="card-text">
                <span class="badge badge-default">{% trans 'optional' %}</span>
                {% for tag in opt_project.get_tags  %}
                {% if forloop.counter|divisibleby:5 %}
                <span class="badge badge-danger">
                {% elif forloop.counter|divisibleby:4 %}
                <span class="badge badge-warning">
                {% elif forloop.counter|divisibleby:3 %}
                <span class="badge badge-info">
                {% elif forloop.counter|divisibleby:2 %}
                <span class="badge badge-success">
                {% else %}
                <span class="badge badge-primary">
                {% endif %}
                    {{ tag }}
                </span>
                {% endfor %}
            </p>
            <h4 class="card-title">{{ opt_project.name }}</h4>
            <p class="card-text">
                {% autoescape off %}{{ opt_project.description|truncatewords_html:12 }}{% endautoescape %}
            </p>
            <a href="{% url 'projects:detail_project' opt_project.id %}" class="btn btn-primary">{% trans 'Go to project' %}</a>
        </div>
        <div class="card-footer">
            <small class="text-muted">
                {% blocktrans with updated_at=opt_project.updated_at|timesince %}
                Last updated {{ updated_at }} ago
                {% endblocktrans %}
            </small>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

mysite/projects/templates/projects/project_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

mysite/projects/templates/projects/userproject_create.html
{% extends 'core/index.html' %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <form action="{% url 'projects:create_user_project' %}" method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="{% trans 'Save' %}" />
</form>
{% endblock %}

mysite/projects/templates/projects/userproject_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    USERPROJECT LIST
</body>
</html>