mysite/core/urls.py
# encoding: utf-8
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),  # translations

    url('^bot/$', views.CommandReceiveView.as_view(), name='command_receive'),

    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password_reset/complete/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^accounts/profile/$', views.ProfileView.as_view(), name='profile'),

    url(r'^$', views.IndexView.as_view(), name='index'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

from django.conf import settings


urlpatterns = [
    url(r'^', include('core.urls', namespace='core')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('social_django.urls', namespace='social')),
]

# urlpatterns += i18n_patterns(
#     url(r'^', include('core.urls', namespace='core')),
# )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mysite/core/models.py
from django.db import models

# Create your models here.

mysite/core/forms.py
# encoding: utf-8

mysite/core/views.py
import json
import telepot
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from django.template.loader import render_to_string
from django.http import HttpResponseForbidden, HttpResponseBadRequest, JsonResponse



TELEGRAM_BOT_TOKEN = '308828925:AAFbww2ge3WxWcsYDXsdy5-PlLBCQWS97QQ'

bot = telepot.Bot(TELEGRAM_BOT_TOKEN)


def _display_help():
    return 'you asked for helpo? ahaha'


#def _display_planetpy_feed():
   # return render_to_string('feed.md', {'items': parse_planetpy_rss()})
def repeat_all_messages(message): # Название функции не играет никакой роли, в $
    bot.sendMessage(message.chat.id, message.text)



class CommandReceiveView(generic.View):
    def post(self, request):
        # if bot_token != TELEGRAM_BOT_TOKEN:
        #     return HttpResponseForbidden('Invalid token')

        commands = {
            '/start': _display_help,
            'help': _display_help,
            'feed': repeat_all_messages,
        }

        raw = request.body.decode('utf-8')

        try:
            payload = json.loads(raw)
        except ValueError:
            return HttpResponseBadRequest('Invalid request body')
        else:
            chat_id = payload['message']['chat']['id']
            cmd = payload['message'].get('text')  # command

            func = commands.get(cmd.split()[0].lower())
            if func:
                bot.sendMessage(chat_id, func(), parse_mode='Markdown')
            else:
                bot.sendMessage(chat_id, 'I do not understand you, Sir!')

        return JsonResponse({}, status=200)

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(CommandReceiveView, self).dispatch(request, *args, **kwargs)



class IndexView(generic.TemplateView):
    template_name = 'core/index.html'


class LoginView(auth_views.LoginView):
    template_name = 'core/login.html'


class LogoutView(auth_views.LogoutView):
    template_name = 'core/logout.html'


class PasswordResetView(auth_views.PasswordResetView):
    template_name = 'core/password_reset.html'
    success_url = reverse_lazy('core:password_reset_done')
    email_template_name = 'core/password_reset_email.html'


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    success_url = reverse_lazy('core:password_reset_complete')
    template_name = 'core/password_reset_confirm.html'


class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'core/password_reset_complete.html'


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'core/password_reset_done.html'


class ProfileView(LoginRequiredMixin, generic.TemplateView):
    login_url = reverse_lazy('core:login')
    template_name = 'core/profile.html'

    # def get_context_data(self, **kwargs):
    #
    #     return super().get_context_data(**kwargs)

mysite/core/templates/core/blocks/footer.html
<footer class="footer">
    <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
    </div>
</footer>

mysite/core/templates/core/blocks/header.html
{% load i18n %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}


<div class="container">
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded rounded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerHeader" aria-controls="navbarTogglerHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">Brand</a>

        <div class="collapse navbar-collapse" id="navbarTogglerHeader">
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
{#                <li class="nav-item active">#}
{#                    <a class="nav-link" href="#">{% trans 'Home page' %}</a>#}
{#                </li>#}
                <li class="nav-item">
                    <a class="nav-link" href="#">{% trans 'Projects' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">{% trans 'Quizzes' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">{% trans 'Polls' %}</a>
                </li>
{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                        {{ LANGUAGE_CODE|capfirst }}#}
{#                    </a>#}
{#                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">#}
{#                        <ul>#}
{#                        {% for lcode, lname in LANGUAGES %}#}
{#                        {% if lcode == 'en' or lcode == 'fr' or lcode == 'ru' or lcode == 'de' %}#}
{#                        <li class="dropdown-item" onclick="setLanguageCookie('{{ lcode }}');">{{ lname }}</li>#}
{#                        {% endif %}#}
{#                        {% endfor %}#}
{#                        </ul>#}
{#                        <script>#}
{#                            function setLanguageCookie(lcode)#}
{#                                Cookies.set('django_language', lcode);#}
{#                                location.reload();#}
{#                            }#}
{#                        </script>#}
{#                        <a class="dropdown-item" href="#">Action</a>#}
{#                        <a class="dropdown-item" href="#">Another action</a>#}
{#                        <a class="dropdown-item" href="#">Something else here</a>#}
{#                    </div>#}

{#                </li>#}
            </ul>
            <form action="{% url 'core:set_language' %}" method="post" class="form-inline my-2 my-lg-0" style="margin-right: 60px">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}" />
                <select name="language" class="form-control mr-sm-2">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        {% if language.code == 'en' or language.code == 'fr' or language.code == 'ru' or language.code == 'de' %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                        {% endif %}
                    {% endfor %}
                </select>
                <input type="submit" value="{% trans 'Go' %}" class="btn btn-outline-success my-2 my-sm-0"/>
            </form>
            <div>
                {% if user.is_authenticated %}
                <a class="btn btn-outline-info" href="{% url 'core:logout' %}">{% trans 'Logout' %}</a>
                {% else %}
                <a class="btn btn-outline-info" href="{% url 'core:login' %}">{% trans 'Login' %}</a>
                {% endif %}
            </div>
        </div>
    </nav>
</div>