mysite/core/urls.py
# encoding: utf-8
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),  # translations

    url('^bot/$', views.CommandReceiveView.as_view(), name='command_receive'),

    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password_reset/complete/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^accounts/profile/$', views.ProfileView.as_view(), name='profile'),

    url(r'^$', views.IndexView.as_view(), name='index'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

from django.conf import settings


urlpatterns = [
    url(r'^', include('core.urls', namespace='core')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('social_django.urls', namespace='social')),
]

# urlpatterns += i18n_patterns(
#     url(r'^', include('core.urls', namespace='core')),
# )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mysite/core/models.py
from django.db import models

# Create your models here.

mysite/core/forms.py
# encoding: utf-8

mysite/core/views.py
import json
import telepot
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from django.template.loader import render_to_string
from django.http import HttpResponseForbidden, HttpResponseBadRequest, JsonResponse



TELEGRAM_BOT_TOKEN = '308828925:AAFbww2ge3WxWcsYDXsdy5-PlLBCQWS97QQ'

bot = telepot.Bot(TELEGRAM_BOT_TOKEN)


def _display_help():
    return 'you asked for helpo? ahaha'


#def _display_planetpy_feed():
   # return render_to_string('feed.md', {'items': parse_planetpy_rss()})
def repeat_all_messages(message): # Название функции не играет никакой роли, в $
    bot.sendMessage(message.chat.id, message.text)



class CommandReceiveView(generic.View):
    def post(self, request):
        # if bot_token != TELEGRAM_BOT_TOKEN:
        #     return HttpResponseForbidden('Invalid token')

        commands = {
            '/start': _display_help,
            'help': _display_help,
            'feed': repeat_all_messages,
        }

        raw = request.body.decode('utf-8')

        try:
            payload = json.loads(raw)
        except ValueError:
            return HttpResponseBadRequest('Invalid request body')
        else:
            chat_id = payload['message']['chat']['id']
            cmd = payload['message'].get('text')  # command

            func = commands.get(cmd.split()[0].lower())
            if func:
                bot.sendMessage(chat_id, func(), parse_mode='Markdown')
            else:
                bot.sendMessage(chat_id, 'I do not understand you, Sir!')

        return JsonResponse({}, status=200)

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(CommandReceiveView, self).dispatch(request, *args, **kwargs)



class IndexView(generic.TemplateView):
    template_name = 'core/index.html'


class LoginView(auth_views.LoginView):
    template_name = 'core/login.html'


class LogoutView(auth_views.LogoutView):
    template_name = 'core/logout.html'


class PasswordResetView(auth_views.PasswordResetView):
    template_name = 'core/password_reset.html'
    success_url = reverse_lazy('core:password_reset_done')
    email_template_name = 'core/password_reset_email.html'


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    success_url = reverse_lazy('core:password_reset_complete')
    template_name = 'core/password_reset_confirm.html'


class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'core/password_reset_complete.html'


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'core/password_reset_done.html'


class ProfileView(LoginRequiredMixin, generic.TemplateView):
    login_url = reverse_lazy('core:login')
    template_name = 'core/profile.html'

    # def get_context_data(self, **kwargs):
    #
    #     return super().get_context_data(**kwargs)

mysite/core/templates/core/index.html
{% load i18n %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <!-- Current language: {{ LANGUAGE_CODE }} -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}{% endblock %}</title>

    <!-- jQuery -->
    <script src="{% static 'core/js/libs/jquery-3.2.1.js' %}"></script>

    <!-- Cookies -->
    <script src="{% static 'core/js/libs/js.cookie.js' %}"></script>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'core/css/libs/bootstrap.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="{% static 'core/js/libs/bootstrap.js' %}"></script>

    <link rel="stylesheet" href="{% static 'core/css/footer.css' %}">

    {% block head_scripts %}{% endblock %}
</head>
<body class="{% block body_class %}{% endblock %}">
    {% include 'core/blocks/header.html' %}

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    {% include 'core/blocks/footer.html' %}

    {% block body_scripts %}{% endblock %}
</body>
</html>

mysite/core/templates/core/login.html
{% extends "core/index.html" %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block head_scripts %}
    <link rel="stylesheet" href="{% static 'core/css/libs/bootstrap-social.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
{% endblock %}

{% block content %}
<div class="jumbotron">
    {% if next and next != '/accounts/profile/' %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {% if user.is_authenticated %}
        {% trans "Your account doesn't have access to this page. To proceed, please login with an account that has access." %}
        {% else %}
        {% trans 'Please login to see this page.' %}
        {% endif %}
    </div>
    {% endif %}

    <form method="post" action="{% url 'core:login' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="{% trans 'Login' %}" class="btn btn-success" style="width: 120px"/>
        <a href="{% url 'core:password_reset' %}" class="pull-right">{% trans 'Lost password?' %}</a>
        <input type="hidden" name="next" value="{{ next }}" />
    </form>

    <p>&nbsp;</p>
    <p>{% trans 'Sign in with' %}:</p>
    <p>
        <a href="{% url "social:begin" "github" %}" class="btn btn-social btn-github" style="width: 150px;margin-right: 10px;margin-bottom: 10px">
            <span class="fa fa-github"></span>
             GitHub
        </a>
        <a href="{% url "social:begin" "bitbucket-oauth2" %}" class="btn btn-social btn-bitbucket" style="width: 150px;margin-right: 10px;margin-bottom: 10px">
            <span class="fa fa-bitbucket"></span>
             BitBucket
        </a>
        <a href="{% url "social:begin" "google-oauth2" %}" class="btn btn-social btn-google" style="width: 150px;margin-right: 10px;margin-bottom: 10px">
            <span class="fa fa-google"></span>
             Google+
        </a>
        <a href="{% url "social:begin" "yandex-oauth2" %}" class="btn btn-social btn-yahoo" style="width: 150px;margin-right: 10px;margin-bottom: 10px">
            <span class="fa fa-yahoo"></span>
             Yandex
        </a>
        <a href="{% url "social:begin" "vk-oauth2" %}" class="btn btn-social btn-vk" style="width: 150px;margin-bottom: 10px">
            <span class="fa fa-vk"></span>
             ВКонтакте
        </a>
    </p>
</div>



{% endblock %}

mysite/core/templates/core/logout.html
{% extends "core/index.html" %}

{% load i18n %}

{% block title %}{% trans 'Logout' %}{% endblock %}

{% block content %}
<div class="jumbotron">
    <h2>{% trans 'Logged out.' %}</h2>
    <h4>{% trans 'Thanks for spending some quality time with the Web site today.' %}</h4>
    <p>&nbsp;</p>
    <p><a href="{% url 'core:login' %}">{% trans 'Login again' %}</a></p>
</div>
{% endblock %}

mysite/core/templates/core/password_reset.html
{% extends "core/index.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="jumbotron">
    <form method="post" action="{% url 'core:password_reset' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="{% trans 'Reset' %}" class="btn btn-success" />
    </form>
</div>
{% endblock %}

mysite/core/templates/core/password_reset_complete.html
{% extends "core/index.html" %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}

<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% trans 'Login' %}</a></p>

{% endblock %}

mysite/core/templates/core/password_reset_confirm.html
{% extends "core/index.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="jumbotron">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="{% trans 'Reset' %}" class="btn btn-success" />
    </form>
</div>
{% endblock %}

mysite/core/templates/core/password_reset_done.html
{% extends "core/index.html" %}

{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="jumbotron">
    <h2>{% trans 'Password reset sent' %}</h2>
    <p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>
    <p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>
</div>
{% endblock %}

mysite/core/templates/core/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'core:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

mysite/core/templates/core/profile.html
{% extends "core/index.html" %}

{% block content %}

{% endblock %}

mysite/core/templates/core/signin.html
{% extends "core/index.html" %}

{% block title %}Sign in{% endblock %}

{% block content %}

{% endblock %}